version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540